# Generated by Django 5.2.4 on 2025-08-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_culturalevent'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_destinations',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='planner.destination'),
        ),
    ]
