# Generated by Django 5.2.4 on 2025-08-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
    ]
