# Generated by Django 5.2.4 on 2025-08-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_read_by_user1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_read_by_user2',
            field=models.BooleanField(default=True),
        ),
    ]
