# Generated by Django 5.2.4 on 2025-08-24 11:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_conversation_is_read_by_user1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('tourist', 'vendor')},
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='service',
        ),
    ]
