# Generated by Django 5.2.4 on 2025-08-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_culturalevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destination_images/'),
        ),
    ]
