# Generated by Django 5.2.4 on 2025-08-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_destination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='destination',
            name='review_count',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
