# Generated by Django 5.2.4 on 2025-10-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_destination_rating_destination_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='destination',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
