# Generated by Django 5.2.4 on 2025-08-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_service_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('HOTEL', 'Hotel'), ('GUIDE', 'Tour Guide'), ('TRANSPORT', 'Transportation'), ('<django.db.models.fields.files.ImageField>', 'Cover Image')], max_length=50),
        ),
    ]
