# Generated by Django 5.2.4 on 2025-08-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
