# Generated by Django 5.2.4 on 2025-08-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_service_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=4.8, max_digits=3),
        ),
        migrations.AddField(
            model_name='service',
            name='review_count',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
