# Generated by Django 5.2.4 on 2025-08-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_service_rating_service_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Commission percentage at the time of booking', max_digits=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the payment was confirmed', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_gateway_txn_id',
            field=models.CharField(blank=True, help_text='Transaction ID from the payment gateway', max_length=100, null=True),
        ),
    ]
